name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t website.com/my-app:${{ github.sha }}
          docker push website.com/my-app:${{ github.sha }}

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v2
        with:
          version: v1.22.0

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f deployment/kubernetes/k8s_deployment.yaml
          kubectl set image deployment/my-app my-app=website.com/my-app:${{ github.sha }}

      - name: Post-deployment verification
        run: |
          kubectl rollout status deployment/my-app